// Common / local names people search by. Added to the starter tests only;
// the lab can edit them per test in Settings → Tests & prices.
export const ALIASES = {
  SEMEN: 'sperm, sperm test, sperm count, semen, SFA, fertility, male fertility',
  CBC: 'blood count, cbc, complete blood, blood picture, khoon',
  CBCS: 'cbc smear, blood picture, peripheral smear, cbc with ps, blood count smear',
  HB: 'hb, hemoglobin, haemoglobin, khoon, blood',
  ESR: 'esr, sed rate',
  BSF: 'sugar, fasting sugar, fbs, glucose, blood sugar fasting',
  BSR: 'sugar, random sugar, rbs, glucose',
  BSPP: 'sugar, pp sugar, post meal, 2hr sugar, ppbs',
  HBA1C: 'hba1c, a1c, sugar average, diabetes, 3 month sugar',
  LFT: 'liver, liver test, jigar, jaundice, bilirubin, sgpt, alt, ast',
  RFT: 'kidney, kidney test, gurda, renal, urea creatinine, kft',
  LIPID: 'cholesterol, lipid, fats, triglycerides, ldl hdl',
  TSH: 'thyroid, thyroid test, tsh',
  TFT: 'thyroid, thyroid profile, t3 t4 tsh',
  URE: 'urine, urine r/e, urine test, urine routine, pishab, dc',
  UCS: 'urine culture, urine c/s, pishab culture, culture',
  WIDAL: 'typhoid, widal, typhoid test, enteric fever, fever',
  TYPHI: 'typhoid, typhidot, typhoid test, fever',
  MP: 'malaria, mp, malaria parasite, fever',
  DENGNS1: 'dengue, ns1, dengue test, fever',
  DENGAB: 'dengue, igm igg, dengue antibodies',
  HBSAG: 'hepatitis b, hbsag, hep b, jaundice, kala yaraqan',
  HCV: 'hepatitis c, hcv, anti hcv, hep c',
  HIV: 'hiv, aids, hiv test',
  VITD: 'vitamin d, vit d, 25 oh, vitamin d3',
  B12: 'vitamin b12, b12, cobalamin',
  CRP: 'crp, c reactive protein, infection, inflammation',
  UA: 'uric acid, gout, gout test',
  CREAT: 'creatinine, kidney, gurda',
  UREA: 'urea, kidney',
  ELEC: 'electrolytes, sodium potassium, na k',
  CA: 'calcium, ca',
  FERR: 'ferritin, iron store, iron',
  IRON: 'iron, serum iron, tibc',
  PT: 'pt inr, prothrombin, inr, blood thinning',
  APTT: 'aptt, ptt, clotting',
  BG: 'blood group, blood type, rh factor',
  PSA: 'psa, prostate',
  PREG: 'pregnancy, pregnancy test, hcg, urine pregnancy',
  BHCG: 'beta hcg, pregnancy, hcg',
  STOOL: 'stool, stool test, stool r/e, pakhana, motion',
  AMH: 'amh, ovarian reserve, fertility',
  PRL: 'prolactin, prl',
  LH: 'lh, hormone',
  FSH: 'fsh, hormone',
  E2: 'estradiol, e2, oestrogen',
  TESTO: 'testosterone, male hormone',
  HISTS: 'biopsy, histopathology, tissue',
  PAP: 'pap smear, cervical screening',
  FNAC: 'fnac, aspiration, lump',
};
